### ISSUE TITLE
Implement single page splash page (v1)

### ISSUE THREAD

**Issue by koobs** [cosites/propertyoptions#3]
- [x] Logo 
- [x] Body text
- [x] Responsive
- [ ] Favicon (moved to #5)
- [ ] Background image (moved to #5)
- [ ] Contact details (moved to (#5)

**Comment by koobs** [comment]
Client feedback below. Will move favicon, contact details and image items form this issue and close this as complete.

![Screen Shot 2023-05-08 at 4 46 21 pm](https://user-images.githubusercontent.com/1011612/236754696-e38a7e09-a985-469d-9b37-05002bc5c310.png)
